# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
-  
  env:
  - CGO_ENABLED=0
  main: ./cmd/
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - ppc64le
  - arm64
  ignore:
  - goos: darwin
    goarch: ppc64le
archives:
  - wrap_in_directory: false
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-snapshot"
#release:
#  draft: true
changelog:
  skip: true
