apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: multinet
spec:
  version: {{ .TagName }}
  homepage: https://github.com/k8snetworkplumbingwg/kubectl-multinet
  shortDescription: "Shows pods' network-status of multi-net-spec"
  description: |
    Shows pods' network-status annotation, defined in NPWG multi-net-spec,
    https://github.com/k8snetworkplumbingwg/multi-net-spec.
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/k8snetworkplumbingwg/kubectl-multinet/releases/download/{{ .TagName }}/kubectl-multinet_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-multinet
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/k8snetworkplumbingwg/kubectl-multinet/releases/download/{{ .TagName }}/kubectl-multinet_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}
    bin: kubectl-multinet
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/k8snetworkplumbingwg/kubectl-multinet/releases/download/{{ .TagName }}/kubectl-multinet_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-multinet
