on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest] # windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

# Uncomment this to use github action's cache
#    - uses: actions/cache@v2
#      with:
#        path: ~/go/pkg/mod
#        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#        restore-keys: |
#          ${{ runner.os }}-go-

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Revive
      if: matrix.os != 'macos-latest'
      run: |
        GO111MODULE=off go get github.com/mgechev/revive
        $(go env GOPATH)/bin/revive -exclude ./vendor/... ./... # this is ouput for user
        $(go env GOPATH)/bin/revive -exclude ./vendor/... ./...| xargs -0 -r false # this is for github actions

# Uncomment this to use github action's script (but it cannot be used for PR, yet...)
#    - name: Run Revive Action by building from repository
#      uses: morphy2k/revive-action@v1.4.1
#      with:
#        exclude: "./vendor/..."
#        name: "Revive"
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run go fmt
      run: diff -u <(echo -n) <(gofmt -d -s .)

    - name: Run go vet
      run: go vet ./...

#    - name: Test
#      run: go test ./...
